name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Install Cosign and test presence in path
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: chimbosonic/cgit
          tags: |
            type=sha,format=long
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=cgit
            org.opencontainers.image.description=A hyperfast web frontend for git repositories written in C.
            org.opencontainers.image.authors=Alexis Lowe <alexis.lowe@protonmail.com>
            org.opencontainers.image.documentation=https://github.com/chimbosonic/cgit-container/blob/main/README.md
            org.opencontainers.image.url=https://hub.docker.com/r/chimbosonic/cgit
          
      - name: Build and Push container images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Sign image with a key
        run: |
          echo ${COSIGN_KEY} > /tmp/my_cosign.key && \
          cosign sign --key /tmp/my_cosign.key ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}

      - name: Sign the images with GitHub OIDC Token **not production ready**
        run: cosign sign ${TAGS}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_EXPERIMENTAL: 1