name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # Build the image every Sunday
    - cron: '0 0 * * 0'

jobs:
  build-sign-publish:
    uses: chimbosonic/container-build-tools/.github/workflows/build-publish-container-resuable-workflow.yml@main
    with:
      image-name: cgit
      image-repo-name: chimbosonic
      image-author: Alexis Lowe <alexis.lowe@chimbosonic.com>
      image-description: A hyperfast web frontend for git repositories written in C.
      image-documentation: https://github.com/chimbosonic/cgit-container/blob/main/README.md
    secrets: inherit